// The `typedefs` command of the bin, apart from `cli.ts` so a spec can run
// it without spawning a process.
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { constraintTypeDefs } from './constraint-directive';

const usage = `Usage: nxgt-graphql-validation typedefs [--out <file>]

  typedefs           print the SDL of @constraint
  --out <file>       write it to <file> instead, creating its folder
  --help             show this help
`;

/** The `.graphqls` file's content: a header, then the SDL. */
export function graphqls(): string {
	return `# The @constraint directive of @nxgt/graphql-validation, for your IDE.\n# Generated by \`nxgt-graphql-validation typedefs\`: do not edit.\n\n${constraintTypeDefs}`;
}

/**
 * Runs the bin on `argv`: 0 done, 1 the file could not be written, 2 a usage
 * error (nxgt-mongo-backup's convention).
 */
export async function main(argv: readonly string[]): Promise<number> {
	const [command, ...rest] = argv;
	if (command === undefined || command === '--help' || command === '-h') {
		process.stdout.write(usage);
		return command === undefined ? 2 : 0;
	}
	if (command !== 'typedefs') {
		process.stderr.write(`Unknown command "${command}".\n\n${usage}`);
		return 2;
	}
	if (rest.length === 0) {
		process.stdout.write(graphqls());
		return 0;
	}
	const [flag, out, ...extra] = rest;
	if (flag !== '--out' || !out || extra.length > 0) {
		process.stderr.write(`Unexpected arguments: ${rest.join(' ')}\n\n${usage}`);
		return 2;
	}
	try {
		await mkdir(dirname(out), { recursive: true });
		await writeFile(out, graphqls());
	} catch (error) {
		process.stderr.write(`typedefs failed: ${(error as Error).message}\n`);
		return 1;
	}
	process.stdout.write(`Wrote ${out}\n`);
	return 0;
}
