// The `typedefs` command of the bin, apart from `cli.ts` so a spec can run
// it without spawning a process. Its flags read as `nxgt-graphql-scalars
// typedefs`' do, so both bins are used the same way.
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { constraintTypeDefs } from './constraint-directive';

/** Where `--out` writes when it is given no file. */
export const DEFAULT_OUT = 'generated/graphql/constraint.graphqls';

const usage = `Usage: nxgt-graphql-validation typedefs [--out [<file>]]

  typedefs           print the SDL of @constraint
  --out [<file>]     write it to <file> instead, creating its folder
                     (default: ${DEFAULT_OUT})
  --help, -h         show this help
`;

/** The `.graphqls` file's content: a header, then the SDL. */
export function graphqls(): string {
	return `# The @constraint directive of @nxgt/graphql-validation, for your IDE.\n# Generated by \`nxgt-graphql-validation typedefs\`: do not edit.\n\n${constraintTypeDefs}`;
}

function refuse(message: string): number {
	process.stderr.write(`${message}\n\n${usage}`);
	return 2;
}

/**
 * Runs the bin on `argv`: 0 done, 1 the file could not be written, 2 a usage
 * error (nxgt-mongo-backup's convention). `--help` anywhere wins.
 */
export async function main(argv: readonly string[]): Promise<number> {
	if (argv.includes('--help') || argv.includes('-h')) {
		process.stdout.write(usage);
		return 0;
	}
	const [command, ...rest] = argv;
	if (command === undefined) return refuse('No command.');
	if (command !== 'typedefs') return refuse(`Unknown command "${command}".`);
	if (rest.length === 0) {
		process.stdout.write(graphqls());
		return 0;
	}
	const [flag, file, ...extra] = rest;
	if (
		flag !== '--out' ||
		extra.length > 0 ||
		file === '' ||
		file?.startsWith('-')
	) {
		return refuse(`Unexpected arguments: ${rest.join(' ')}`);
	}
	const out = file ?? DEFAULT_OUT;
	try {
		await mkdir(dirname(out), { recursive: true });
		await writeFile(out, graphqls());
	} catch (error) {
		process.stderr.write(`typedefs failed: ${(error as Error).message}\n`);
		return 1;
	}
	process.stdout.write(`Wrote ${out}\n`);
	return 0;
}
