import { afterAll, afterEach, describe, expect, spyOn, test } from 'bun:test';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildSchema, graphql } from 'graphql';
import { pickScalars } from './pick-scalars';
import { scalarResolvers, scalarTypeDefs } from './scalars';
import { DEFAULT_OUT, graphqls, main } from './typedefs-command';

const SHIPPED = join(import.meta.dir, '../graphql/scalars.graphqls');

describe('the typedefs command', () => {
	const out = spyOn(process.stdout, 'write').mockImplementation(() => true);
	const err = spyOn(process.stderr, 'write').mockImplementation(() => true);
	afterEach(() => {
		out.mockClear();
		err.mockClear();
	});
	afterAll(() => {
		out.mockRestore();
		err.mockRestore();
	});

	test('prints every scalar, as scalarTypeDefs declares them', async () => {
		expect(await main(['typedefs'])).toBe(0);
		const printed = String(out.mock.calls[0]?.[0]);
		expect(printed).toContain(`${scalarTypeDefs}\n`);
		expect(printed).toStartWith('# The scalars of @nxgt/graphql-scalars');
		expect(printed).toContain(
			'# Generated by `nxgt-graphql-scalars typedefs`: do not edit.',
		);
		const types = buildSchema(`${printed}\ntype Query { a: DateTime }`);
		expect(Object.keys(scalarResolvers).every((n) => types.getType(n))).toBe(
			true,
		);
	});

	test('prints only the named scalars, as pickScalars declares them', async () => {
		expect(await main(['typedefs', 'DateTime', 'URL'])).toBe(0);
		const printed = String(out.mock.calls[0]?.[0]);
		expect(printed).toContain(`${pickScalars('DateTime', 'URL').typeDefs}\n`);
		expect(printed).not.toContain('scalar UUID');
	});

	test('answers an unknown name with 2 and pickScalars message, which lists the names', async () => {
		expect(await main(['typedefs', 'DateTime', 'Nope'])).toBe(2);
		const message = String(err.mock.calls[0]?.[0]);
		expect(message).toStartWith('pickScalars: no scalar is named "Nope".');
		expect(message).toContain('DateTime');
		// Then the usage, as every other usage error.
		expect(message).toContain('.\n\nUsage: nxgt-graphql-scalars typedefs');
		expect(out).not.toHaveBeenCalled();
	});

	test('writes it to --out <file>, creating the folder', async () => {
		const dir = await mkdtemp(join(tmpdir(), 'graphqls-'));
		try {
			const file = join(dir, 'schema/scalars.graphqls');
			expect(await main(['typedefs', 'Port', '--out', file])).toBe(0);
			expect(await readFile(file, 'utf8')).toBe(graphqls(['Port']));
		} finally {
			await rm(dir, { recursive: true, force: true });
		}
	});

	test('writes --out with no file to generated/graphql/scalars.graphqls of the current directory', async () => {
		const dir = await mkdtemp(join(tmpdir(), 'graphqls-'));
		const here = process.cwd();
		try {
			process.chdir(dir);
			expect(await main(['typedefs', '--out'])).toBe(0);
			expect(await readFile(join(dir, DEFAULT_OUT), 'utf8')).toBe(graphqls());
			expect(DEFAULT_OUT).toBe('generated/graphql/scalars.graphqls');
		} finally {
			process.chdir(here);
			await rm(dir, { recursive: true, force: true });
		}
	});

	test('fails with 1 and one line when the file cannot be written', async () => {
		const dir = await mkdtemp(join(tmpdir(), 'graphqls-'));
		try {
			expect(await main(['typedefs', '--out', dir])).toBe(1);
			expect(String(err.mock.calls[0]?.[0])).toStartWith('typedefs failed: ');
		} finally {
			await rm(dir, { recursive: true, force: true });
		}
	});

	test('answers --help with 0, and nothing, a wrong command or wrong arguments with 2', async () => {
		expect(await main(['--help'])).toBe(0);
		expect(await main(['typedefs', '--help'])).toBe(0);
		expect(await main(['typedefs', 'DateTime', '-h'])).toBe(0);
		err.mockClear();
		expect(await main([])).toBe(2);
		expect(await main(['schema'])).toBe(2);
		expect(await main(['typedefs', '--out', 'a', 'b'])).toBe(2);
		expect(await main(['typedefs', '--force'])).toBe(2);
		expect(await main(['typedefs', '--out=x'])).toBe(2);
		expect(await main(['typedefs', '--out', '--out'])).toBe(2);
		expect(await main(['typedefs', '--out', ''])).toBe(2);
		// The names come first: `--out DateTime` is no file name.
		expect(await main(['typedefs', '--out', 'DateTime'])).toBe(2);
		expect(await main(['typedefs', 'toString'])).toBe(2);
		expect(await main(['typedefs', 'constructor'])).toBe(2);
		expect(String(err.mock.calls[0]?.[0])).toStartWith('No command.');
		expect(String(err.mock.calls[1]?.[0])).toStartWith(
			'Unknown command "schema".',
		);
	});
});

describe('graphql/scalars.graphqls, shipped in the package', () => {
	test('is what `typedefs` prints: regenerate it with `bun run --cwd packages/graphql-scalars typedefs:write`', async () => {
		const shipped = await readFile(SHIPPED, 'utf8');
		if (shipped !== graphqls()) {
			throw new Error(
				'graphql/scalars.graphqls is out of date. Regenerate it: `bun run --cwd packages/graphql-scalars typedefs:write`, then commit it.',
			);
		}
	});

	test('declares every scalar, and the resolvers bind to it end to end', async () => {
		const schema = buildSchema(
			`${await readFile(SHIPPED, 'utf8')}\ntype Query { a: DateTime, port(n: Port!): Port }`,
		);
		for (const [name, scalar] of Object.entries(scalarResolvers)) {
			const type = schema.getType(name);
			if (type === undefined) throw new Error(`${name} is not declared`);
			Object.assign(type, scalar.toConfig());
		}
		const query = schema.getQueryType()?.getFields();
		if (query === undefined) throw new Error('no Query');
		const a = query['a'];
		const port = query['port'];
		if (a === undefined || port === undefined) throw new Error('no field');
		a.resolve = () => new Date('2024-03-10T12:00:00Z');
		port.resolve = (_: unknown, args: { n: number }) => args.n;
		expect(await graphql({ schema, source: '{ a port(n: 8080) }' })).toEqual({
			data: { a: '2024-03-10T12:00:00.000Z', port: 8080 },
		});
		const refused = await graphql({ schema, source: '{ port(n: 70000) }' });
		expect(refused.errors?.[0]?.message).toStartWith(
			'Port cannot represent this input',
		);
	});
});
