// The `typedefs` command of the bin, apart from `cli.ts` so a spec can run
// it without spawning a process.
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { pickScalars } from './pick-scalars';
import { type ScalarName, scalarResolvers, scalarTypeDefs } from './scalars';

/** Where `--out` with no file writes, relative to the current directory. */
export const DEFAULT_OUT = 'generated/graphql/scalars.graphqls';

const usage = `Usage: nxgt-graphql-scalars typedefs [<Name>...] [--out [<file>]]

  typedefs           print the SDL of every scalar
  <Name>...          only these scalars (DateTime URL), as pickScalars does;
                     the names come before --out
  --out [<file>]     write it to <file> instead, creating its folder;
                     without a file: ${DEFAULT_OUT}
  --help, -h         show this help
`;

function isScalarName(text: string): boolean {
	return Object.hasOwn(scalarResolvers, text);
}

/**
 * The `.graphqls` file's content: a header, then the SDL of every scalar, or
 * of the named ones. Throws pickScalars' own error for an unknown name.
 */
export function graphqls(names: readonly string[] = []): string {
	const typeDefs =
		names.length === 0
			? scalarTypeDefs
			: pickScalars(...(names as ScalarName[])).typeDefs;
	return `# The scalars of @nxgt/graphql-scalars, for your IDE.\n# Generated by \`nxgt-graphql-scalars typedefs\`: do not edit.\n\n${typeDefs}\n`;
}

/**
 * Runs the bin on `argv`: 0 done, 1 the file could not be written, 2 a usage
 * error (nxgt-mongo-backup's convention).
 */
export async function main(argv: readonly string[]): Promise<number> {
	const [command, ...rest] = argv;
	if (argv.includes('--help') || argv.includes('-h')) {
		process.stdout.write(usage);
		return 0;
	}
	if (command === undefined) {
		process.stderr.write(`No command.\n\n${usage}`);
		return 2;
	}
	if (command !== 'typedefs') {
		process.stderr.write(`Unknown command "${command}".\n\n${usage}`);
		return 2;
	}
	const flagAt = rest.findIndex((arg) => arg.startsWith('-'));
	const names = flagAt === -1 ? rest : rest.slice(0, flagAt);
	const flags = flagAt === -1 ? [] : rest.slice(flagAt);
	const [flag, file, ...extra] = flags;
	if (
		flags.length > 0 &&
		(flag !== '--out' ||
			extra.length > 0 ||
			file === '' ||
			file?.startsWith('-') ||
			// `--out DateTime`: a name after the flag, not a file name.
			(file !== undefined && isScalarName(file)))
	) {
		process.stderr.write(`Unexpected arguments: ${rest.join(' ')}\n\n${usage}`);
		return 2;
	}
	let content: string;
	try {
		content = graphqls(names);
	} catch (error) {
		process.stderr.write(`${(error as Error).message}\n`);
		return 2;
	}
	if (flag === undefined) {
		process.stdout.write(content);
		return 0;
	}
	const out = file ?? DEFAULT_OUT;
	try {
		await mkdir(dirname(out), { recursive: true });
		await writeFile(out, content);
	} catch (error) {
		process.stderr.write(`typedefs failed: ${(error as Error).message}\n`);
		return 1;
	}
	process.stdout.write(`Wrote ${out}\n`);
	return 0;
}
