import { z } from "zod";
import { scalarSchemas } from "@nxgt/graphql-scalars";

export const zAllScalars = z.strictObject({
	base64: scalarSchemas.Base64.nullish(),
	base64List: z.union([z.array(scalarSchemas.Base64), z.custom<z.input<typeof scalarSchemas.Base64>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Base64))]).nullish(),
	base64URL: scalarSchemas.Base64URL.nullish(),
	base64URLList: z.union([z.array(scalarSchemas.Base64URL), z.custom<z.input<typeof scalarSchemas.Base64URL>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Base64URL))]).nullish(),
	bigInt: scalarSchemas.BigInt.nullish(),
	bigIntList: z.union([z.array(scalarSchemas.BigInt), z.custom<z.input<typeof scalarSchemas.BigInt>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.BigInt))]).nullish(),
	cidRv4: scalarSchemas.CIDRv4.nullish(),
	cidRv4List: z.union([z.array(scalarSchemas.CIDRv4), z.custom<z.input<typeof scalarSchemas.CIDRv4>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.CIDRv4))]).nullish(),
	cidRv6: scalarSchemas.CIDRv6.nullish(),
	cidRv6List: z.union([z.array(scalarSchemas.CIDRv6), z.custom<z.input<typeof scalarSchemas.CIDRv6>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.CIDRv6))]).nullish(),
	countryCode: scalarSchemas.CountryCode.nullish(),
	countryCodeList: z.union([z.array(scalarSchemas.CountryCode), z.custom<z.input<typeof scalarSchemas.CountryCode>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.CountryCode))]).nullish(),
	cuid2: scalarSchemas.Cuid2.nullish(),
	cuid2List: z.union([z.array(scalarSchemas.Cuid2), z.custom<z.input<typeof scalarSchemas.Cuid2>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Cuid2))]).nullish(),
	currency: scalarSchemas.Currency.nullish(),
	currencyList: z.union([z.array(scalarSchemas.Currency), z.custom<z.input<typeof scalarSchemas.Currency>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Currency))]).nullish(),
	date: scalarSchemas.Date.nullish(),
	dateList: z.union([z.array(scalarSchemas.Date), z.custom<z.input<typeof scalarSchemas.Date>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Date))]).nullish(),
	dateTime: scalarSchemas.DateTime.nullish(),
	dateTimeList: z.union([z.array(scalarSchemas.DateTime), z.custom<z.input<typeof scalarSchemas.DateTime>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.DateTime))]).nullish(),
	duration: scalarSchemas.Duration.nullish(),
	durationList: z.union([z.array(scalarSchemas.Duration), z.custom<z.input<typeof scalarSchemas.Duration>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Duration))]).nullish(),
	emailAddress: scalarSchemas.EmailAddress.nullish(),
	emailAddressList: z.union([z.array(scalarSchemas.EmailAddress), z.custom<z.input<typeof scalarSchemas.EmailAddress>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.EmailAddress))]).nullish(),
	emoji: scalarSchemas.Emoji.nullish(),
	emojiList: z.union([z.array(scalarSchemas.Emoji), z.custom<z.input<typeof scalarSchemas.Emoji>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Emoji))]).nullish(),
	guid: scalarSchemas.GUID.nullish(),
	guidList: z.union([z.array(scalarSchemas.GUID), z.custom<z.input<typeof scalarSchemas.GUID>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.GUID))]).nullish(),
	hsla: scalarSchemas.HSLA.nullish(),
	hslaList: z.union([z.array(scalarSchemas.HSLA), z.custom<z.input<typeof scalarSchemas.HSLA>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.HSLA))]).nullish(),
	hsl: scalarSchemas.HSL.nullish(),
	hslList: z.union([z.array(scalarSchemas.HSL), z.custom<z.input<typeof scalarSchemas.HSL>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.HSL))]).nullish(),
	hexColorCode: scalarSchemas.HexColorCode.nullish(),
	hexColorCodeList: z.union([z.array(scalarSchemas.HexColorCode), z.custom<z.input<typeof scalarSchemas.HexColorCode>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.HexColorCode))]).nullish(),
	hexadecimal: scalarSchemas.Hexadecimal.nullish(),
	hexadecimalList: z.union([z.array(scalarSchemas.Hexadecimal), z.custom<z.input<typeof scalarSchemas.Hexadecimal>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Hexadecimal))]).nullish(),
	hostname: scalarSchemas.Hostname.nullish(),
	hostnameList: z.union([z.array(scalarSchemas.Hostname), z.custom<z.input<typeof scalarSchemas.Hostname>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Hostname))]).nullish(),
	iban: scalarSchemas.IBAN.nullish(),
	ibanList: z.union([z.array(scalarSchemas.IBAN), z.custom<z.input<typeof scalarSchemas.IBAN>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.IBAN))]).nullish(),
	ip: scalarSchemas.IP.nullish(),
	ipList: z.union([z.array(scalarSchemas.IP), z.custom<z.input<typeof scalarSchemas.IP>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.IP))]).nullish(),
	iPv4: scalarSchemas.IPv4.nullish(),
	iPv4List: z.union([z.array(scalarSchemas.IPv4), z.custom<z.input<typeof scalarSchemas.IPv4>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.IPv4))]).nullish(),
	iPv6: scalarSchemas.IPv6.nullish(),
	iPv6List: z.union([z.array(scalarSchemas.IPv6), z.custom<z.input<typeof scalarSchemas.IPv6>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.IPv6))]).nullish(),
	isbn: scalarSchemas.ISBN.nullish(),
	isbnList: z.union([z.array(scalarSchemas.ISBN), z.custom<z.input<typeof scalarSchemas.ISBN>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.ISBN))]).nullish(),
	jsonObject: scalarSchemas.JSONObject.nullish(),
	jsonObjectList: z.union([z.array(scalarSchemas.JSONObject), z.custom<z.input<typeof scalarSchemas.JSONObject>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.JSONObject))]).nullish(),
	json: scalarSchemas.JSON.nullish(),
	jsonList: z.union([z.array(scalarSchemas.JSON), z.custom<z.input<typeof scalarSchemas.JSON>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.JSON))]).nullish(),
	jwt: scalarSchemas.JWT.nullish(),
	jwtList: z.union([z.array(scalarSchemas.JWT), z.custom<z.input<typeof scalarSchemas.JWT>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.JWT))]).nullish(),
	ksuid: scalarSchemas.KSUID.nullish(),
	ksuidList: z.union([z.array(scalarSchemas.KSUID), z.custom<z.input<typeof scalarSchemas.KSUID>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.KSUID))]).nullish(),
	latitude: scalarSchemas.Latitude.nullish(),
	latitudeList: z.union([z.array(scalarSchemas.Latitude), z.custom<z.input<typeof scalarSchemas.Latitude>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Latitude))]).nullish(),
	localDateTime: scalarSchemas.LocalDateTime.nullish(),
	localDateTimeList: z.union([z.array(scalarSchemas.LocalDateTime), z.custom<z.input<typeof scalarSchemas.LocalDateTime>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.LocalDateTime))]).nullish(),
	localTime: scalarSchemas.LocalTime.nullish(),
	localTimeList: z.union([z.array(scalarSchemas.LocalTime), z.custom<z.input<typeof scalarSchemas.LocalTime>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.LocalTime))]).nullish(),
	locale: scalarSchemas.Locale.nullish(),
	localeList: z.union([z.array(scalarSchemas.Locale), z.custom<z.input<typeof scalarSchemas.Locale>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Locale))]).nullish(),
	long: scalarSchemas.Long.nullish(),
	longList: z.union([z.array(scalarSchemas.Long), z.custom<z.input<typeof scalarSchemas.Long>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Long))]).nullish(),
	longitude: scalarSchemas.Longitude.nullish(),
	longitudeList: z.union([z.array(scalarSchemas.Longitude), z.custom<z.input<typeof scalarSchemas.Longitude>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Longitude))]).nullish(),
	mac: scalarSchemas.MAC.nullish(),
	macList: z.union([z.array(scalarSchemas.MAC), z.custom<z.input<typeof scalarSchemas.MAC>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.MAC))]).nullish(),
	nanoID: scalarSchemas.NanoID.nullish(),
	nanoIDList: z.union([z.array(scalarSchemas.NanoID), z.custom<z.input<typeof scalarSchemas.NanoID>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.NanoID))]).nullish(),
	negativeFloat: scalarSchemas.NegativeFloat.nullish(),
	negativeFloatList: z.union([z.array(scalarSchemas.NegativeFloat), z.custom<z.input<typeof scalarSchemas.NegativeFloat>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.NegativeFloat))]).nullish(),
	negativeInt: scalarSchemas.NegativeInt.nullish(),
	negativeIntList: z.union([z.array(scalarSchemas.NegativeInt), z.custom<z.input<typeof scalarSchemas.NegativeInt>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.NegativeInt))]).nullish(),
	nonEmptyString: scalarSchemas.NonEmptyString.nullish(),
	nonEmptyStringList: z.union([z.array(scalarSchemas.NonEmptyString), z.custom<z.input<typeof scalarSchemas.NonEmptyString>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.NonEmptyString))]).nullish(),
	nonNegativeFloat: scalarSchemas.NonNegativeFloat.nullish(),
	nonNegativeFloatList: z.union([z.array(scalarSchemas.NonNegativeFloat), z.custom<z.input<typeof scalarSchemas.NonNegativeFloat>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.NonNegativeFloat))]).nullish(),
	nonNegativeInt: scalarSchemas.NonNegativeInt.nullish(),
	nonNegativeIntList: z.union([z.array(scalarSchemas.NonNegativeInt), z.custom<z.input<typeof scalarSchemas.NonNegativeInt>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.NonNegativeInt))]).nullish(),
	nonPositiveFloat: scalarSchemas.NonPositiveFloat.nullish(),
	nonPositiveFloatList: z.union([z.array(scalarSchemas.NonPositiveFloat), z.custom<z.input<typeof scalarSchemas.NonPositiveFloat>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.NonPositiveFloat))]).nullish(),
	nonPositiveInt: scalarSchemas.NonPositiveInt.nullish(),
	nonPositiveIntList: z.union([z.array(scalarSchemas.NonPositiveInt), z.custom<z.input<typeof scalarSchemas.NonPositiveInt>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.NonPositiveInt))]).nullish(),
	objectID: scalarSchemas.ObjectID.nullish(),
	objectIDList: z.union([z.array(scalarSchemas.ObjectID), z.custom<z.input<typeof scalarSchemas.ObjectID>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.ObjectID))]).nullish(),
	phoneNumber: scalarSchemas.PhoneNumber.nullish(),
	phoneNumberList: z.union([z.array(scalarSchemas.PhoneNumber), z.custom<z.input<typeof scalarSchemas.PhoneNumber>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.PhoneNumber))]).nullish(),
	port: scalarSchemas.Port.nullish(),
	portList: z.union([z.array(scalarSchemas.Port), z.custom<z.input<typeof scalarSchemas.Port>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Port))]).nullish(),
	positiveFloat: scalarSchemas.PositiveFloat.nullish(),
	positiveFloatList: z.union([z.array(scalarSchemas.PositiveFloat), z.custom<z.input<typeof scalarSchemas.PositiveFloat>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.PositiveFloat))]).nullish(),
	positiveInt: scalarSchemas.PositiveInt.nullish(),
	positiveIntList: z.union([z.array(scalarSchemas.PositiveInt), z.custom<z.input<typeof scalarSchemas.PositiveInt>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.PositiveInt))]).nullish(),
	rgba: scalarSchemas.RGBA.nullish(),
	rgbaList: z.union([z.array(scalarSchemas.RGBA), z.custom<z.input<typeof scalarSchemas.RGBA>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.RGBA))]).nullish(),
	rgb: scalarSchemas.RGB.nullish(),
	rgbList: z.union([z.array(scalarSchemas.RGB), z.custom<z.input<typeof scalarSchemas.RGB>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.RGB))]).nullish(),
	sHA256: scalarSchemas.SHA256.nullish(),
	sHA256List: z.union([z.array(scalarSchemas.SHA256), z.custom<z.input<typeof scalarSchemas.SHA256>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.SHA256))]).nullish(),
	sHA512: scalarSchemas.SHA512.nullish(),
	sHA512List: z.union([z.array(scalarSchemas.SHA512), z.custom<z.input<typeof scalarSchemas.SHA512>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.SHA512))]).nullish(),
	safeInt: scalarSchemas.SafeInt.nullish(),
	safeIntList: z.union([z.array(scalarSchemas.SafeInt), z.custom<z.input<typeof scalarSchemas.SafeInt>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.SafeInt))]).nullish(),
	semVer: scalarSchemas.SemVer.nullish(),
	semVerList: z.union([z.array(scalarSchemas.SemVer), z.custom<z.input<typeof scalarSchemas.SemVer>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.SemVer))]).nullish(),
	time: scalarSchemas.Time.nullish(),
	timeList: z.union([z.array(scalarSchemas.Time), z.custom<z.input<typeof scalarSchemas.Time>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Time))]).nullish(),
	timeZone: scalarSchemas.TimeZone.nullish(),
	timeZoneList: z.union([z.array(scalarSchemas.TimeZone), z.custom<z.input<typeof scalarSchemas.TimeZone>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.TimeZone))]).nullish(),
	timestamp: scalarSchemas.Timestamp.nullish(),
	timestampList: z.union([z.array(scalarSchemas.Timestamp), z.custom<z.input<typeof scalarSchemas.Timestamp>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Timestamp))]).nullish(),
	ulid: scalarSchemas.ULID.nullish(),
	ulidList: z.union([z.array(scalarSchemas.ULID), z.custom<z.input<typeof scalarSchemas.ULID>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.ULID))]).nullish(),
	url: scalarSchemas.URL.nullish(),
	urlList: z.union([z.array(scalarSchemas.URL), z.custom<z.input<typeof scalarSchemas.URL>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.URL))]).nullish(),
	uuid: scalarSchemas.UUID.nullish(),
	uuidList: z.union([z.array(scalarSchemas.UUID), z.custom<z.input<typeof scalarSchemas.UUID>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.UUID))]).nullish(),
	uuiDv4: scalarSchemas.UUIDv4.nullish(),
	uuiDv4List: z.union([z.array(scalarSchemas.UUIDv4), z.custom<z.input<typeof scalarSchemas.UUIDv4>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.UUIDv4))]).nullish(),
	uuiDv7: scalarSchemas.UUIDv7.nullish(),
	uuiDv7List: z.union([z.array(scalarSchemas.UUIDv7), z.custom<z.input<typeof scalarSchemas.UUIDv7>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.UUIDv7))]).nullish(),
	utcOffset: scalarSchemas.UtcOffset.nullish(),
	utcOffsetList: z.union([z.array(scalarSchemas.UtcOffset), z.custom<z.input<typeof scalarSchemas.UtcOffset>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.UtcOffset))]).nullish(),
	void: scalarSchemas.Void.nullish(),
	voidList: z.union([z.array(scalarSchemas.Void), z.custom<z.input<typeof scalarSchemas.Void>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.Void))]).nullish(),
	xid: scalarSchemas.XID.nullish(),
	xidList: z.union([z.array(scalarSchemas.XID), z.custom<z.input<typeof scalarSchemas.XID>>((value) => value != null && !Array.isArray(value)).transform((value): unknown[] => [value]).pipe(z.array(scalarSchemas.XID))]).nullish(),
});
export type AllScalars = z.output<typeof zAllScalars>;

export const zQueryAllArgs = z.object({
	get input() {
		return zAllScalars;
	},
});
export type QueryAllArgs = z.output<typeof zQueryAllArgs>;

export const zQuery = z.object({
	__typename: z.literal("Query").optional(),
	all: z.boolean().nullish(),
});
export type Query = z.output<typeof zQuery>;

export const zAllQueryVariables = z.object({
	get input() {
		return zAllScalars;
	},
});
export type AllQueryVariables = z.input<typeof zAllQueryVariables>;

export const zAllQuery = z.object({
	all: z.boolean().nullable(),
});
export type AllQuery = z.output<typeof zAllQuery>;
